runtime: java11
env: flex
instance_class: F2
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp, mysql"
entrypoint: java -noverify -jar apirest-0.0.1-SNAPSHOT.jar

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: --Connection string given by GCP and setting with region and others
    username: root
    password: root
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1

    max-active: 15
    max-idle: 10
    max-wait: 8000